language: bash

sudo: required

branches:
  only:
    - master
    - develop
    - volatile
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^support\/.*$/
    - /^hotfix\/.*$/

env:
  global:
    - CITM_HOST="d41d8cd98f00b204e9800998ecf8427e"
    - SIMBOL_PROFILE="TRAVIS"
    - USER_USERNAME="travis"
    - PATH="${PATH}:${HOME}/bin"
  matrix:
    - CONTEXT=installer MODULE=-
    - CONTEXT=execute   MODULE=core
    - CONTEXT=coverage  MODULE=core
    - CONTEXT=execute   MODULE=git
    - CONTEXT=coverage  MODULE=git
    - CONTEXT=execute   MODULE=hgd
    - CONTEXT=coverage  MODULE=hgd

matrix:
  fast_finish: true

  allow_failures:
    - env: CONTEXT=coverage  MODULE=git
    - env: CONTEXT=coverage  MODULE=hgd
    - env: CONTEXT=execute   MODULE=tunnel
    - env: CONTEXT=coverage  MODULE=tunnel
    - env: CONTEXT=execute   MODULE=tutorial
    - env: CONTEXT=coverage  MODULE=tutorial
    - env: CONTEXT=execute   MODULE=xplm
    - env: CONTEXT=coverage  MODULE=xplm

before_install:
  - sudo apt-get update -qq
  - share/unit/citm before_install

install:
  - share/unit/citm install

before_script:
  - share/unit/citm before_script

script:
  - share/unit/citm script

after_success:
  - share/unit/citm after_success

after_failure:
  - share/unit/citm after_failure

after_script:
  - share/unit/citm after_script

# vim:sw=2:ts=2:et
