language: c    #. Not really, it's actually bash

branches:
  only:
    - master
    - develop
    - volatile
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^support\/.*$/
    - /^hotfix\/.*$/

env:
  global:
    - CITM_HOST="d41d8cd98f00b204e9800998ecf8427e"
    - SIMBOL_PROFILE="TRAVIS"
    - USER_USERNAME="travis"
    - PATH="${PATH}:${HOME}/bin"
  matrix:
    - CONTEXT=execute MODULE=core
    # CONTEXT=execute MODULE=tutorial #. nima/simbol#15  util
    - CONTEXT=execute MODULE=util     #. nima/simbol#4
    - CONTEXT=execute MODULE=dns      #. nima/simbol#10  util
    - CONTEXT=execute MODULE=net      #. nima/simbol#7   dns
    - CONTEXT=execute MODULE=git      #. nima/simbol#9   net
    - CONTEXT=execute MODULE=hgd      #. nima/simbol#3   util net
    - CONTEXT=execute MODULE=tunnel   #. nima/simbol#18  util net dns
    - CONTEXT=execute MODULE=remote   #. nima/simbol#13  util hgd dns
    - CONTEXT=execute MODULE=gpg      #. nima/simbol#5
    - CONTEXT=execute MODULE=vault    #. nima/simbol#17  gpg
    - CONTEXT=execute MODULE=help     #. nima/simbol#19
    - CONTEXT=execute MODULE=xplm     #. nima/simbol#29
    - CONTEXT=installer MODULE=-

matrix:
  allow_failures:
    - env: CONTEXT=execute MODULE=xplm
    - env: CONTEXT=execute MODULE=tunnel

before_install:
  - sudo apt-get update -qq
  - share/unit/citm before_install

install:
  - share/unit/citm install

before_script:
  - share/unit/citm before_script

script:
  - share/unit/citm script

after_success:
  - share/unit/citm after_success

after_failure:
  - share/unit/citm after_failure

after_script:
  - share/unit/citm after_script
