safe: true
lsi: false
highlighter: rouge
source: .

title: simbol
description: Modular shell-scripting framework - 90% native bash, 10% phat!
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker
